"""
Central configuration and skills taxonomy.
500+ skills across 15 categories with aliases for robust matching.
"""

SKILLS_TAXONOMY = {
    "Programming Languages": [
        {"name": "Python", "aliases": ["python3", "py", "python programming"], "weight": 1.0},
        {"name": "Java", "aliases": ["java8", "java11", "java17", "core java"], "weight": 1.0},
        {"name": "JavaScript", "aliases": ["js", "javascript es6", "ecmascript", "es2022"], "weight": 1.0},
        {"name": "TypeScript", "aliases": ["ts", "typescript 4", "typescript 5"], "weight": 0.9},
        {"name": "C++", "aliases": ["cpp", "c plus plus", "c++17", "c++20"], "weight": 0.9},
        {"name": "C", "aliases": ["c programming", "c language", "c99", "c11"], "weight": 0.8},
        {"name": "Go", "aliases": ["golang", "go lang", "go programming"], "weight": 0.9},
        {"name": "Rust", "aliases": ["rust lang", "rust programming"], "weight": 0.8},
        {"name": "Kotlin", "aliases": ["kotlin android", "jvm kotlin"], "weight": 0.8},
        {"name": "Swift", "aliases": ["swift ios", "swift programming"], "weight": 0.7},
        {"name": "R", "aliases": ["r programming", "r language", "rstudio"], "weight": 0.8},
        {"name": "Scala", "aliases": ["scala programming", "functional scala"], "weight": 0.8},
        {"name": "PHP", "aliases": ["php7", "php8", "php programming"], "weight": 0.7},
        {"name": "Ruby", "aliases": ["ruby lang", "ruby programming"], "weight": 0.7},
        {"name": "C#", "aliases": ["csharp", "c sharp", "dotnet c#", ".net c#"], "weight": 0.8},
        {"name": "MATLAB", "aliases": ["matlab programming"], "weight": 0.6},
        {"name": "Shell Scripting", "aliases": ["bash", "bash scripting", "shell script", "zsh"], "weight": 0.8},
        {"name": "PowerShell", "aliases": ["powershell scripting", "ps1"], "weight": 0.6},
        {"name": "Julia", "aliases": ["julia lang", "julia programming"], "weight": 0.5},
        {"name": "Dart", "aliases": ["dart programming", "flutter dart"], "weight": 0.6},
    ],
    "Web Development": [
        {"name": "React", "aliases": ["reactjs", "react.js", "react hooks", "react 18"], "weight": 1.0},
        {"name": "Angular", "aliases": ["angularjs", "angular 2+", "angular 17"], "weight": 0.9},
        {"name": "Vue.js", "aliases": ["vuejs", "vue 3", "vue.js"], "weight": 0.9},
        {"name": "Next.js", "aliases": ["nextjs", "next 14", "server side react"], "weight": 0.9},
        {"name": "Node.js", "aliases": ["nodejs", "node js", "express node"], "weight": 1.0},
        {"name": "Django", "aliases": ["django rest", "django framework", "django python"], "weight": 0.9},
        {"name": "FastAPI", "aliases": ["fast api", "fastapi python"], "weight": 0.9},
        {"name": "Flask", "aliases": ["flask python", "flask rest", "flask web"], "weight": 0.8},
        {"name": "Spring Boot", "aliases": ["springboot", "spring framework", "spring mvc"], "weight": 0.9},
        {"name": "GraphQL", "aliases": ["graph ql", "graphql api"], "weight": 0.8},
        {"name": "REST API", "aliases": ["restful api", "rest services", "api design", "restful services"], "weight": 1.0},
        {"name": "HTML", "aliases": ["html5", "html css", "semantic html"], "weight": 0.8},
        {"name": "CSS", "aliases": ["css3", "sass", "scss", "css modules"], "weight": 0.8},
        {"name": "Tailwind CSS", "aliases": ["tailwindcss", "tailwind"], "weight": 0.7},
        {"name": "Redux", "aliases": ["redux toolkit", "react redux", "state management"], "weight": 0.7},
        {"name": "WebSocket", "aliases": ["websockets", "ws", "socket.io"], "weight": 0.7},
        {"name": "Microservices", "aliases": ["microservice architecture", "service mesh"], "weight": 0.9},
        {"name": "Svelte", "aliases": ["sveltekit", "svelte framework"], "weight": 0.6},
    ],
    "Data Science & Machine Learning": [
        {"name": "Machine Learning", "aliases": ["ml", "supervised learning", "unsupervised learning", "ml algorithms"], "weight": 1.0},
        {"name": "Deep Learning", "aliases": ["dl", "neural networks", "deep neural networks", "dnn"], "weight": 1.0},
        {"name": "Natural Language Processing", "aliases": ["nlp", "text analytics", "text mining", "computational linguistics"], "weight": 1.0},
        {"name": "Computer Vision", "aliases": ["cv", "image recognition", "object detection", "image processing"], "weight": 0.9},
        {"name": "TensorFlow", "aliases": ["tensorflow 2", "tf", "tf2", "keras tensorflow"], "weight": 1.0},
        {"name": "PyTorch", "aliases": ["torch", "pytorch lightning", "pytorch geometric"], "weight": 1.0},
        {"name": "Scikit-learn", "aliases": ["sklearn", "scikit learn", "scikit-learn"], "weight": 1.0},
        {"name": "Keras", "aliases": ["keras api", "tf.keras"], "weight": 0.8},
        {"name": "Pandas", "aliases": ["pandas python", "dataframe", "pd"], "weight": 1.0},
        {"name": "NumPy", "aliases": ["numpy python", "np", "numerical python"], "weight": 0.9},
        {"name": "Hugging Face", "aliases": ["huggingface", "transformers library", "hugging face transformers"], "weight": 0.9},
        {"name": "LLM", "aliases": ["large language models", "llms", "gpt", "language models", "llm fine-tuning"], "weight": 1.0},
        {"name": "RAG", "aliases": ["retrieval augmented generation", "rag pipeline", "vector search rag"], "weight": 0.9},
        {"name": "LangChain", "aliases": ["langchain python", "langchain agents"], "weight": 0.9},
        {"name": "Reinforcement Learning", "aliases": ["rl", "reward learning", "q-learning", "deep rl"], "weight": 0.7},
        {"name": "Feature Engineering", "aliases": ["feature selection", "feature extraction", "feature creation"], "weight": 0.9},
        {"name": "Model Deployment", "aliases": ["ml deployment", "model serving", "model productionization"], "weight": 0.9},
        {"name": "MLflow", "aliases": ["mlflow tracking", "ml lifecycle"], "weight": 0.8},
        {"name": "XGBoost", "aliases": ["xgb", "gradient boosting", "extreme gradient boosting"], "weight": 0.8},
        {"name": "LightGBM", "aliases": ["lgbm", "light gbm"], "weight": 0.7},
        {"name": "spaCy", "aliases": ["spacy nlp", "spacy python"], "weight": 0.7},
        {"name": "BERT", "aliases": ["bert model", "bert fine-tuning", "roberta", "distilbert"], "weight": 0.8},
        {"name": "OpenCV", "aliases": ["cv2", "opencv python", "open cv"], "weight": 0.7},
        {"name": "Matplotlib", "aliases": ["matplotlib python", "pyplot"], "weight": 0.7},
        {"name": "Seaborn", "aliases": ["seaborn python", "sns"], "weight": 0.6},
        {"name": "Plotly", "aliases": ["plotly express", "plotly dash"], "weight": 0.7},
        {"name": "Statistical Analysis", "aliases": ["statistics", "hypothesis testing", "statistical modelling", "statistical inference"], "weight": 0.9},
        {"name": "A/B Testing", "aliases": ["ab testing", "split testing", "experimentation"], "weight": 0.8},
        {"name": "Time Series", "aliases": ["time series analysis", "forecasting", "arima", "lstm forecasting"], "weight": 0.8},
        {"name": "Recommendation Systems", "aliases": ["recommender systems", "collaborative filtering", "matrix factorization"], "weight": 0.7},
    ],
    "Data Engineering": [
        {"name": "Apache Spark", "aliases": ["pyspark", "spark streaming", "spark sql", "databricks spark"], "weight": 1.0},
        {"name": "Apache Kafka", "aliases": ["kafka streaming", "kafka connect", "event streaming"], "weight": 0.9},
        {"name": "Apache Airflow", "aliases": ["airflow dags", "airflow scheduling", "workflow orchestration"], "weight": 0.9},
        {"name": "dbt", "aliases": ["dbt core", "data build tool", "dbt cloud"], "weight": 0.8},
        {"name": "ETL", "aliases": ["etl pipelines", "extract transform load", "data pipelines", "data integration"], "weight": 1.0},
        {"name": "Data Warehousing", "aliases": ["data warehouse", "dwh", "olap", "dimensional modelling"], "weight": 0.9},
        {"name": "Apache Hadoop", "aliases": ["hadoop hdfs", "mapreduce", "hadoop ecosystem"], "weight": 0.7},
        {"name": "Databricks", "aliases": ["databricks platform", "delta lake"], "weight": 0.9},
        {"name": "Great Expectations", "aliases": ["ge", "data quality", "data validation"], "weight": 0.7},
        {"name": "Flink", "aliases": ["apache flink", "flink streaming"], "weight": 0.7},
        {"name": "Hive", "aliases": ["apache hive", "hive sql", "hql"], "weight": 0.6},
    ],
    "Cloud & DevOps": [
        {"name": "AWS", "aliases": ["amazon web services", "aws cloud", "amazon aws", "ec2", "s3", "lambda"], "weight": 1.0},
        {"name": "Google Cloud", "aliases": ["gcp", "google cloud platform", "bigquery", "gke"], "weight": 1.0},
        {"name": "Azure", "aliases": ["microsoft azure", "azure cloud", "azure devops"], "weight": 1.0},
        {"name": "Docker", "aliases": ["containerization", "docker container", "dockerfile", "docker compose"], "weight": 1.0},
        {"name": "Kubernetes", "aliases": ["k8s", "container orchestration", "kubectl", "helm"], "weight": 1.0},
        {"name": "Terraform", "aliases": ["infrastructure as code", "iac", "terraform hcl"], "weight": 0.9},
        {"name": "CI/CD", "aliases": ["continuous integration", "continuous deployment", "devops pipeline", "jenkins pipeline"], "weight": 1.0},
        {"name": "GitHub Actions", "aliases": ["gha", "github ci", "github workflows"], "weight": 0.8},
        {"name": "Jenkins", "aliases": ["jenkins ci", "jenkins pipeline", "jenkins build"], "weight": 0.8},
        {"name": "Ansible", "aliases": ["ansible automation", "ansible playbook"], "weight": 0.7},
        {"name": "Linux", "aliases": ["linux admin", "ubuntu", "centos", "linux server", "unix"], "weight": 0.9},
        {"name": "Nginx", "aliases": ["nginx server", "nginx configuration"], "weight": 0.7},
        {"name": "Prometheus", "aliases": ["prometheus monitoring", "metrics collection"], "weight": 0.7},
        {"name": "Grafana", "aliases": ["grafana dashboards", "monitoring dashboards"], "weight": 0.7},
        {"name": "Site Reliability Engineering", "aliases": ["sre", "reliability engineering", "slo sli"], "weight": 0.8},
        {"name": "GitLab CI", "aliases": ["gitlab pipeline", "gitlab ci/cd"], "weight": 0.7},
    ],
    "Databases": [
        {"name": "SQL", "aliases": ["sql queries", "structured query language", "sql programming", "ansi sql"], "weight": 1.0},
        {"name": "PostgreSQL", "aliases": ["postgres", "postgresql db", "psql"], "weight": 1.0},
        {"name": "MySQL", "aliases": ["mysql db", "mysql server"], "weight": 0.9},
        {"name": "MongoDB", "aliases": ["mongo", "mongodb atlas", "nosql mongodb", "mongoose"], "weight": 0.9},
        {"name": "Redis", "aliases": ["redis cache", "redis db", "in-memory cache"], "weight": 0.8},
        {"name": "Elasticsearch", "aliases": ["elastic search", "elk stack", "opensearch"], "weight": 0.8},
        {"name": "BigQuery", "aliases": ["google bigquery", "bq", "gcp bigquery"], "weight": 0.8},
        {"name": "Snowflake", "aliases": ["snowflake db", "snowflake data warehouse"], "weight": 0.8},
        {"name": "Cassandra", "aliases": ["apache cassandra", "cassandra db"], "weight": 0.7},
        {"name": "DynamoDB", "aliases": ["aws dynamodb", "amazon dynamodb"], "weight": 0.7},
        {"name": "Neo4j", "aliases": ["graph database", "neo4j db"], "weight": 0.6},
        {"name": "SQLite", "aliases": ["sqlite3", "sqlite database"], "weight": 0.6},
        {"name": "Oracle", "aliases": ["oracle db", "oracle sql", "plsql"], "weight": 0.7},
        {"name": "Vector Database", "aliases": ["pinecone", "weaviate", "chromadb", "faiss", "qdrant", "milvus"], "weight": 0.8},
    ],
    "Tools & Practices": [
        {"name": "Git", "aliases": ["git version control", "github", "gitlab", "bitbucket", "git workflow"], "weight": 1.0},
        {"name": "Agile", "aliases": ["agile methodology", "agile development", "agile scrum"], "weight": 0.9},
        {"name": "Scrum", "aliases": ["scrum methodology", "sprint planning", "daily standup"], "weight": 0.8},
        {"name": "JIRA", "aliases": ["jira software", "jira board", "atlassian jira"], "weight": 0.7},
        {"name": "System Design", "aliases": ["system architecture", "high level design", "low level design", "hld lld"], "weight": 0.9},
        {"name": "Design Patterns", "aliases": ["software design patterns", "oop patterns", "gof patterns"], "weight": 0.8},
        {"name": "Data Structures", "aliases": ["dsa", "algorithms", "data structures algorithms"], "weight": 0.9},
        {"name": "Unit Testing", "aliases": ["unit tests", "pytest", "jest", "junit", "test driven development", "tdd"], "weight": 0.8},
        {"name": "API Testing", "aliases": ["postman", "api test", "swagger testing"], "weight": 0.7},
        {"name": "Code Review", "aliases": ["peer review", "pull request review"], "weight": 0.7},
        {"name": "Jupyter Notebook", "aliases": ["jupyter", "ipynb", "jupyter lab"], "weight": 0.7},
        {"name": "VS Code", "aliases": ["vscode", "visual studio code"], "weight": 0.5},
        {"name": "Linux CLI", "aliases": ["command line", "terminal", "cli tools"], "weight": 0.7},
        {"name": "Swagger / OpenAPI", "aliases": ["swagger docs", "openapi spec", "api documentation"], "weight": 0.7},
    ],
    "AI & Emerging Tech": [
        {"name": "Prompt Engineering", "aliases": ["prompt design", "chain-of-thought", "few-shot prompting", "llm prompting"], "weight": 0.9},
        {"name": "Fine-tuning LLMs", "aliases": ["llm fine-tuning", "lora", "qlora", "instruction tuning", "sft"], "weight": 0.9},
        {"name": "LangGraph", "aliases": ["lang graph", "langgraph agents"], "weight": 0.8},
        {"name": "CrewAI", "aliases": ["crew ai", "crewai agents", "multi agent framework"], "weight": 0.7},
        {"name": "Generative AI", "aliases": ["genai", "gen ai", "generative models", "gpt api", "openai api"], "weight": 0.9},
        {"name": "Vector Embeddings", "aliases": ["text embeddings", "sentence embeddings", "semantic embeddings"], "weight": 0.8},
        {"name": "MLOps", "aliases": ["ml ops", "machine learning operations", "ml platform"], "weight": 0.9},
        {"name": "AI Ethics", "aliases": ["responsible ai", "ai fairness", "bias detection", "model explainability", "xai"], "weight": 0.7},
        {"name": "Stable Diffusion", "aliases": ["diffusion models", "image generation", "text to image"], "weight": 0.6},
        {"name": "AutoML", "aliases": ["automated ml", "auto ml", "h2o automl", "automl tools"], "weight": 0.6},
    ],
    "Soft Skills": [
        {"name": "Communication", "aliases": ["verbal communication", "written communication", "stakeholder communication"], "weight": 0.8},
        {"name": "Problem Solving", "aliases": ["analytical thinking", "critical thinking", "problem analysis"], "weight": 0.9},
        {"name": "Teamwork", "aliases": ["collaboration", "team player", "cross-functional"], "weight": 0.8},
        {"name": "Leadership", "aliases": ["team leadership", "tech lead", "people management"], "weight": 0.8},
        {"name": "Project Management", "aliases": ["pm", "project planning", "delivery management"], "weight": 0.8},
        {"name": "Data-Driven Decision Making", "aliases": ["data driven", "metrics driven", "evidence based"], "weight": 0.8},
        {"name": "Presentation Skills", "aliases": ["presenting", "slide decks", "executive presentations"], "weight": 0.7},
    ],
}

# Flatten all skills for quick lookup
ALL_SKILLS = {}
for category, skills in SKILLS_TAXONOMY.items():
    for skill in skills:
        ALL_SKILLS[skill["name"].lower()] = {
            "name": skill["name"],
            "category": category,
            "aliases": skill.get("aliases", []),
            "weight": skill.get("weight", 1.0),
        }
        for alias in skill.get("aliases", []):
            ALL_SKILLS[alias.lower()] = {
                "name": skill["name"],
                "category": category,
                "aliases": skill.get("aliases", []),
                "weight": skill.get("weight", 1.0),
            }


APP_CONFIG = {
    "max_job_descriptions": 10,
    "min_match_threshold": 0.3,
    "critical_gap_threshold": 0.7,
    "moderate_gap_threshold": 0.4,
    "max_courses_per_skill": 3,
    "report_title": "AI-Powered Skill Gap Analysis Report",
}
