"""
PDF Report Generator
Generates a professional, styled PDF report from SkillGapReport.
Uses ReportLab for full layout control.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics import renderPDF

from core.models import SkillGapReport, GapPriority

# ── Brand Colours ──────────────────────────────────────────────
C_DARK      = colors.HexColor("#0F172A")
C_HEADING   = colors.HexColor("#1E3A5F")
C_ACCENT    = colors.HexColor("#4F46E5")
C_SUCCESS   = colors.HexColor("#059669")
C_WARNING   = colors.HexColor("#D97706")
C_DANGER    = colors.HexColor("#DC2626")
C_MINOR     = colors.HexColor("#6B7280")
C_LIGHT_BG  = colors.HexColor("#F8FAFC")
C_BORDER    = colors.HexColor("#E2E8F0")
C_WHITE     = colors.white
C_PURPLE_BG = colors.HexColor("#EEF2FF")


def generate_pdf_report(report: SkillGapReport) -> bytes:
    """Generate a complete PDF report and return as bytes."""
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18*mm,
        leftMargin=18*mm,
        topMargin=20*mm,
        bottomMargin=18*mm,
        title=f"Skill Gap Report — {report.candidate_name}",
        author="AI Skill Gap Analyser",
    )

    styles = _build_styles()
    story = []

    # ── Cover Header ────────────────────────────────────────────
    story += _header_section(report, styles)
    story.append(Spacer(1, 8*mm))

    # ── Summary Banner ──────────────────────────────────────────
    story += _summary_section(report, styles)
    story.append(Spacer(1, 6*mm))

    # ── Match Score Bar ─────────────────────────────────────────
    story.append(_match_score_bar(report))
    story.append(Spacer(1, 6*mm))

    # ── Stats Row ───────────────────────────────────────────────
    story.append(_stats_table(report, styles))
    story.append(Spacer(1, 8*mm))

    # ── Matched Skills ──────────────────────────────────────────
    if report.matched_skills:
        story += _matched_skills_section(report, styles)
        story.append(Spacer(1, 6*mm))

    # ── Skill Gaps Table ─────────────────────────────────────────
    if report.skill_gaps:
        story += _skill_gaps_section(report, styles)
        story.append(Spacer(1, 6*mm))

    # ── Learning Roadmap ─────────────────────────────────────────
    if report.recommendations:
        story += _recommendations_section(report, styles)
        story.append(Spacer(1, 6*mm))

    # ── Companies Hiring ─────────────────────────────────────────
    if report.top_companies_hiring:
        story += _companies_section(report, styles)
        story.append(Spacer(1, 6*mm))

    # ── Agent Logs ───────────────────────────────────────────────
    story += _agent_logs_section(report, styles)

    # ── Footer ───────────────────────────────────────────────────
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        f"Generated by AI Skill Gap Analyser &nbsp;|&nbsp; {report.analysis_date} &nbsp;|&nbsp; Confidential",
        styles["footer"]
    ))

    doc.build(story, onFirstPage=_add_watermark, onLaterPages=_add_watermark)
    return buffer.getvalue()


def _add_watermark(canvas, doc):
    """Add page number and subtle branding."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(C_MINOR)
    page_num = canvas.getPageNumber()
    canvas.drawRightString(A4[0] - 18*mm, 10*mm, f"Page {page_num}")
    canvas.restoreState()


# ── Section Builders ────────────────────────────────────────────

def _header_section(report, styles):
    elements = []
    # Top colour bar
    bar_data = [["  "]]
    bar = Table(bar_data, colWidths=["100%"], rowHeights=[14])
    bar.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_ACCENT),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
    ]))
    elements.append(bar)
    elements.append(Spacer(1, 5*mm))

    elements.append(Paragraph("AI-POWERED SKILL GAP ANALYSIS REPORT", styles["report_title"]))
    elements.append(Spacer(1, 2*mm))

    # Candidate + role
    info_data = [
        [Paragraph(f"<b>Candidate:</b> {report.candidate_name}", styles["meta"]),
         Paragraph(f"<b>Target Role:</b> {report.target_role}", styles["meta"])],
        [Paragraph(f"<b>Date:</b> {report.analysis_date}", styles["meta"]),
         Paragraph(f"<b>JDs Analysed:</b> {report.job_descriptions_analysed}", styles["meta"])],
    ]
    info_table = Table(info_data, colWidths=["50%", "50%"])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_LIGHT_BG),
        ("GRID", (0, 0), (-1, -1), 0.5, C_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(info_table)
    return elements


def _summary_section(report, styles):
    elements = []
    elements.append(Paragraph("Executive Summary", styles["section_heading"]))
    summary_data = [[Paragraph(report.summary, styles["summary_text"])]]
    summary_table = Table(summary_data, colWidths=["100%"])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_PURPLE_BG),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 1.5, C_ACCENT),
        ("ROUNDEDCORNERS", [4]),
    ]))
    elements.append(summary_table)
    return elements


def _match_score_bar(report):
    """Visual match percentage bar."""
    pct = report.match_percentage
    width = 174 * mm
    bar_w = width * (pct / 100)

    drawing = Drawing(width, 28)
    # Background track
    drawing.add(Rect(0, 8, width, 14, fillColor=C_BORDER, strokeColor=None))
    # Fill
    fill_color = C_SUCCESS if pct >= 70 else (C_WARNING if pct >= 40 else C_DANGER)
    if bar_w > 0:
        drawing.add(Rect(0, 8, bar_w, 14, fillColor=fill_color, strokeColor=None))
    # Label
    drawing.add(String(width + 2, 12, f"{pct}%", fontSize=11, fillColor=C_DARK, fontName="Helvetica-Bold"))
    drawing.add(String(0, 0, "Profile Match", fontSize=8, fillColor=C_MINOR, fontName="Helvetica"))
    return drawing


def _stats_table(report, styles):
    critical = len([g for g in report.skill_gaps if g.priority == GapPriority.CRITICAL])
    moderate = len([g for g in report.skill_gaps if g.priority == GapPriority.MODERATE])
    minor = len([g for g in report.skill_gaps if g.priority == GapPriority.MINOR])

    data = [
        [
            _stat_cell(str(len(report.matched_skills)), "Skills Matched", C_SUCCESS, styles),
            _stat_cell(str(critical), "Critical Gaps", C_DANGER, styles),
            _stat_cell(str(moderate), "Moderate Gaps", C_WARNING, styles),
            _stat_cell(str(minor), "Minor Gaps", C_MINOR, styles),
            _stat_cell(f"{report.estimated_learning_weeks}w", "Est. Timeline", C_ACCENT, styles),
        ]
    ]
    table = Table(data, colWidths=["20%"] * 5)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_LIGHT_BG),
        ("GRID", (0, 0), (-1, -1), 0.5, C_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table


def _stat_cell(value, label, color, styles):
    return [
        Paragraph(f'<font color="{color.hexval()}" size="16"><b>{value}</b></font>', styles["stat_value"]),
        Paragraph(label, styles["stat_label"]),
    ]


def _matched_skills_section(report, styles):
    elements = [Paragraph("✅  Matched Skills", styles["section_heading"])]
    skills_text = " &nbsp;·&nbsp; ".join(
        f'<font color="#059669"><b>{s}</b></font>' for s in report.matched_skills
    )
    data = [[Paragraph(skills_text, styles["skill_pill"])]]
    t = Table(data, colWidths=["100%"])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0FDF4")),
        ("BOX", (0, 0), (-1, -1), 0.5, C_SUCCESS),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(t)
    return elements


def _skill_gaps_section(report, styles):
    elements = [Paragraph("🎯  Skill Gap Analysis", styles["section_heading"])]

    priority_colors = {
        GapPriority.CRITICAL: (C_DANGER, "CRITICAL"),
        GapPriority.MODERATE: (C_WARNING, "MODERATE"),
        GapPriority.MINOR: (C_MINOR, "MINOR"),
    }

    header = [
        Paragraph("<b>Skill</b>", styles["th"]),
        Paragraph("<b>Category</b>", styles["th"]),
        Paragraph("<b>Priority</b>", styles["th"]),
        Paragraph("<b>JD Freq.</b>", styles["th"]),
        Paragraph("<b>Why It Matters</b>", styles["th"]),
    ]
    rows = [header]

    for i, gap in enumerate(report.skill_gaps):
        c, label = priority_colors[gap.priority]
        bg = colors.HexColor("#FFF5F5") if gap.priority == GapPriority.CRITICAL else (
             colors.HexColor("#FFFBEB") if gap.priority == GapPriority.MODERATE else C_WHITE)

        rows.append([
            Paragraph(f"<b>{gap.skill}</b>", styles["td_bold"]),
            Paragraph(gap.category, styles["td"]),
            Paragraph(f'<font color="{c.hexval()}"><b>{label}</b></font>', styles["td_center"]),
            Paragraph(str(gap.frequency_in_jds), styles["td_center"]),
            Paragraph(gap.reason, styles["td_small"]),
        ])

    col_widths = ["18%", "18%", "12%", "8%", "44%"]
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), C_HEADING),
        ("TEXTCOLOR", (0, 0), (-1, 0), C_WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("GRID", (0, 0), (-1, -1), 0.3, C_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    for i, gap in enumerate(report.skill_gaps, 1):
        bg = colors.HexColor("#FFF5F5") if gap.priority == GapPriority.CRITICAL else (
             colors.HexColor("#FFFBEB") if gap.priority == GapPriority.MODERATE else C_WHITE)
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), bg))

    t.setStyle(TableStyle(style_cmds))
    elements.append(t)
    return elements


def _recommendations_section(report, styles):
    elements = [Paragraph("📚  Learning Roadmap", styles["section_heading"])]
    elements.append(Paragraph(
        f"Estimated completion: <b>{report.estimated_learning_weeks} weeks</b> at ~15 hrs/week",
        styles["sub_text"]
    ))
    elements.append(Spacer(1, 3*mm))

    # Group by skill
    skill_courses = {}
    for rec in report.recommendations:
        skill_courses.setdefault(rec.skill, []).append(rec)

    header = [
        Paragraph("<b>Skill</b>", styles["th"]),
        Paragraph("<b>Course</b>", styles["th"]),
        Paragraph("<b>Platform</b>", styles["th"]),
        Paragraph("<b>Duration</b>", styles["th"]),
        Paragraph("<b>Level</b>", styles["th"]),
        Paragraph("<b>Free?</b>", styles["th"]),
    ]
    rows = [header]

    for rec in report.recommendations:
        free_label = Paragraph('<font color="#059669"><b>FREE</b></font>' if rec.is_free else '<font color="#6B7280">Paid</font>', styles["td_center"])
        rows.append([
            Paragraph(f"<b>{rec.skill}</b>", styles["td_bold"]),
            Paragraph(f'<link href="{rec.url}" color="#4F46E5">{rec.title}</link>', styles["td_small"]),
            Paragraph(rec.platform, styles["td"]),
            Paragraph(rec.duration, styles["td"]),
            Paragraph(rec.level, styles["td"]),
            free_label,
        ])

    col_widths = ["16%", "34%", "14%", "12%", "12%", "12%"]
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), C_HEADING),
        ("TEXTCOLOR", (0, 0), (-1, 0), C_WHITE),
        ("GRID", (0, 0), (-1, -1), 0.3, C_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_WHITE, C_LIGHT_BG]),
    ]))
    elements.append(t)
    return elements


def _companies_section(report, styles):
    elements = [Paragraph("🏢  Top Companies Hiring", styles["section_heading"])]
    companies_text = " &nbsp;|&nbsp; ".join(
        f"<b>{c}</b>" for c in report.top_companies_hiring
    )
    elements.append(Paragraph(companies_text, styles["company_text"]))
    return elements


def _agent_logs_section(report, styles):
    elements = [Paragraph("🤖  Agent Pipeline Logs", styles["section_heading"])]
    log_lines = "\n".join(f"• {log}" for log in report.agent_logs[-20:])
    data = [[Paragraph(f'<font face="Courier" size="7">{log_lines}</font>', styles["log_text"])]]
    t = Table(data, colWidths=["100%"])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#94A3B8")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(t)
    return elements


def _build_styles():
    styles = getSampleStyleSheet()

    custom = {
        "report_title": ParagraphStyle("report_title", fontSize=18, fontName="Helvetica-Bold",
                                       textColor=C_HEADING, alignment=TA_CENTER, spaceAfter=4),
        "section_heading": ParagraphStyle("section_heading", fontSize=11, fontName="Helvetica-Bold",
                                          textColor=C_HEADING, spaceBefore=6, spaceAfter=4,
                                          borderPad=2),
        "meta": ParagraphStyle("meta", fontSize=9, fontName="Helvetica", textColor=C_DARK),
        "summary_text": ParagraphStyle("summary_text", fontSize=9.5, fontName="Helvetica",
                                       textColor=C_DARK, leading=14),
        "th": ParagraphStyle("th", fontSize=8.5, fontName="Helvetica-Bold",
                              textColor=C_WHITE, alignment=TA_LEFT),
        "td": ParagraphStyle("td", fontSize=8, fontName="Helvetica", textColor=C_DARK),
        "td_bold": ParagraphStyle("td_bold", fontSize=8.5, fontName="Helvetica-Bold", textColor=C_DARK),
        "td_center": ParagraphStyle("td_center", fontSize=8, fontName="Helvetica",
                                    textColor=C_DARK, alignment=TA_CENTER),
        "td_small": ParagraphStyle("td_small", fontSize=7.5, fontName="Helvetica",
                                   textColor=C_DARK, leading=11),
        "skill_pill": ParagraphStyle("skill_pill", fontSize=8.5, fontName="Helvetica",
                                     textColor=C_DARK, leading=16),
        "stat_value": ParagraphStyle("stat_value", fontSize=18, fontName="Helvetica-Bold",
                                     alignment=TA_CENTER),
        "stat_label": ParagraphStyle("stat_label", fontSize=7.5, fontName="Helvetica",
                                     textColor=C_MINOR, alignment=TA_CENTER),
        "sub_text": ParagraphStyle("sub_text", fontSize=8.5, fontName="Helvetica",
                                   textColor=C_MINOR),
        "company_text": ParagraphStyle("company_text", fontSize=9, fontName="Helvetica",
                                       textColor=C_DARK, leading=16),
        "log_text": ParagraphStyle("log_text", fontSize=7, fontName="Courier",
                                   textColor=colors.HexColor("#94A3B8"), leading=11),
        "footer": ParagraphStyle("footer", fontSize=7.5, fontName="Helvetica",
                                 textColor=C_MINOR, alignment=TA_CENTER),
    }
    styles.add(ParagraphStyle("placeholder"))
    for name, style in custom.items():
        try:
            styles.add(style)
        except Exception:
            pass
    return styles
